In [25]:
# Importação das bibliotecas necessárias e carregamento do dataset
import pandas as pd
from IPython.display import display

dados_ibovespa = pd.read_csv('dados_historicos_ibovespa.csv')

In [26]:
# Inspeção do dataset
print("Dados Iníciais do DataFrame:")
display(dados_ibovespa.head(5)) # As Colunas Data, Vol. e Var% são str deveriam ser object

print("Dados Finais do DataFrame:")
display(dados_ibovespa.tail(5)) # As Colunas Data, Vol. e Var% são str deveriam ser object

print("Quandidade de linhas e colunas:")
print(f"Linhas: {dados_ibovespa.shape[0]}")
print(f"Colunas: {dados_ibovespa.shape[1]}")

Dados Iníciais do DataFrame:

         Data   Último  Abertura   Máxima   Mínima    Vol.    Var%
0  05.06.2024  121.407   121.803  122.170  121.253   8,77M  -0,32%
1  04.06.2024  121.802   122.032  122.032  120.878   8,53M  -0,19%
2  03.06.2024  122.032   122.100  122.495  121.496   8,43M  -0,05%
3  31.05.2024  122.098   122.704  122.837  121.929  15,92M  -0,50%
4  29.05.2024  122.707   123.780  123.780  122.458   8,26M  -0,87%

Dados Finais do DataFrame:

           Data  Último  Abertura  Máxima  Mínima    Vol.    Var%
990  12.06.2020  92.795    94.677  94.703  90.811  12,79M  -2,00%
991  10.06.2020  94.686    96.747  97.646  94.665  11,74M  -2,13%
992  09.06.2020  96.747    97.644  97.644  95.386  11,29M  -0,92%
993  08.06.2020  97.645    94.640  97.693  94.635  11,10M   3,18%
994  05.06.2020  94.637    93.839  97.356  93.839  13,32M   0,86%

Quandidade de linhas e colunas:
Linhas: 995
Colunas: 7

In [27]:
# Tipos dos dados
print("Informações gerais do DataFrame:")
display(dados_ibovespa.info())

Informações gerais do DataFrame:
<class 'pandas.DataFrame'>
RangeIndex: 995 entries, 0 to 994
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Data      995 non-null    str
 1   Último    995 non-null    float64
 2   Abertura  995 non-null    float64
 3   Máxima    995 non-null    float64
 4   Mínima    995 non-null    float64
 5   Vol.      995 non-null    str
 6   Var%      995 non-null    str
dtypes: float64(4), str(3)
memory usage: 54.5 KB

None

Ponto de atenção

O `Dtype` das colunas `Data`, `Vol.` e `Var%` estão com tipo `str`, mas deveriam ser `object`

In [28]:
# Estatística descritiva

print("Descrição estatística do DataFrame:")
display(dados_ibovespa.describe())

Descrição estatística do DataFrame:

           Último    Abertura      Máxima      Mínima
count  995.000000  995.000000  995.000000  995.000000
mean   113.460895  113.433682  114.409564  112.481545
std      9.556273    9.572786    9.439067    9.646551
min     92.376000   92.387000   93.112000   90.148000
25%    106.080500  106.039000  106.993000  105.040500
50%    113.262000  113.228000  114.213000  112.135000
75%    119.889500  119.798000  120.816500  118.961000
max    134.194000  134.194000  134.392000  133.832000

In [29]:
# Missing values

print("Valores ausentes: \n")
missing = dados_ibovespa.isnull().sum()
display(missing)

Valores ausentes:

Data        0
Último      0
Abertura    0
Máxima      0
Mínima      0
Vol.        0
Var%        0
dtype: int64

In [30]:
# Duplicidade

print("Valores Duplicados:")
duplicated = dados_ibovespa.duplicated().sum()
print(duplicated)

datas_duplicadas = dados_ibovespa['Data'].duplicated().sum()
print(f"Quantidade de datas duplicadas: {datas_duplicadas}")

Valores Duplicados:
0
Quantidade de datas duplicadas: 0